# Numpy

The structure of this notebook is inspired by w3schools: https://www.w3schools.com/python/numpy/

NumPy = Numerical Python

What is numpy?
- A library for arrays
- Good for linear algebra
- Fast computation

Why use numpy?
- A lot faster than lists
- Often easier to use
- Great for data science

Code can be found here:
https://github.com/numpy/numpy


In [60]:
import numpy as np

# Iterating arrays

In [61]:
dat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for i in range(3):
    print(f"i={i}:", dat[i])

i=0: [1 2 3]
i=1: [4 5 6]
i=2: [7 8 9]


In [62]:
dat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for i in range(3):
    for j in range(3):
        print('i, j:', dat[i, j])

i, j: 1
i, j: 2
i, j: 3
i, j: 4
i, j: 5
i, j: 6
i, j: 7
i, j: 8
i, j: 9


In [63]:
dat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for dat_i in dat:
    print(dat_i)

[1 2 3]
[4 5 6]
[7 8 9]


In [64]:
dat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for i, dat_i in enumerate(dat):
    print(f"i={i}:", dat_i)

i=0: [1 2 3]
i=1: [4 5 6]
i=2: [7 8 9]


In [65]:
dat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for i, dat_i in enumerate(dat.flat[::2]):
    print(f"i={i}:", dat_i)

i=0: 1
i=1: 3
i=2: 5
i=3: 7
i=4: 9


# Combine multiple arrays

In [66]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.concatenate([dat1, dat2])
print(dat)

[1 2 3 4 5 6]


In [67]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.hstack([dat1, dat2])
print(dat)

[1 2 3 4 5 6]


In [68]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.vstack([dat1, dat2])
print(dat)

[[1 2 3]
 [4 5 6]]


In [69]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat3 = np.vstack([dat1, dat2])
dat = np.hstack([dat3, dat3])
print(dat)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [11]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.stack([dat1, dat2], axis=0)
print(dat)

[[1 2 3]
 [4 5 6]]


In [12]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.stack([dat1, dat2], axis=1)
print(dat)

[[1 4]
 [2 5]
 [3 6]]


# Splitting arrays

In [13]:
dat = np.array([[1, 2, 3], [4, 5, 6]])
dat1, dat2 = dat

print(dat1)

[1 2 3]


In [14]:
dat = np.array([[1, 2, 3], [4, 5, 6]])
dat1, dat2 = np.array_split(dat, 2)
print(dat1, dat2)
print(dat1.shape)

[[1 2 3]] [[4 5 6]]
(1, 3)


In [15]:
dat = np.array([[1, 2, 3], [4, 5, 6]])
dat1, dat2, dat3 = np.array_split(dat, 3)
print(dat1, dat2, dat3)
print(dat1.shape)

[[1 2 3]] [[4 5 6]] []
(1, 3)


In [16]:
dat = np.array([[1, 2, 3], [4, 5, 6]])
dat1, dat2 = np.vsplit(dat, 2)
print(dat1, dat2)
print(dat1.shape)

[[1 2 3]] [[4 5 6]]
(1, 3)


# Searching

In [17]:
dat = np.array([1, 2, 3, 4, 5, 6])
np.where(dat > 3)

(array([3, 4, 5], dtype=int64),)

In [18]:
dat = np.array([1, 2, 3, 4, 5, 6])
dat[np.argmax(dat)]

6

# Sorting

In [19]:
dat = np.array([2, 123, 5, 12, 4, ])
print(np.sort(dat))

[  2   4   5  12 123]


In [20]:
dat = np.array([2, 123, 5, 12, 4, ])
print(np.argsort(dat))

[0 4 2 3 1]


In [21]:
dat = np.array(["as", "asd", "%%%", "12", "b", ])
print(np.sort(dat))

['%%%' '12' 'as' 'asd' 'b']


In [22]:
dat = np.array([[2, 123, 5], [12, 4, 8]])
print(np.sort(dat, axis=1))

[[  2   5 123]
 [  4   8  12]]


In [23]:
dat = np.array([[2, 123, 5], [12, 4, 8]])
print(np.sort(dat, axis=0))

[[  2   4   5]
 [ 12 123   8]]


# Filtering and masking

In [24]:
dat = np.array([2, 123, 5, 12, 4])
idxs = np.where(dat > 10)[0]
print(dat[idxs])

[123  12]


In [25]:
dat = np.array([2, 123, 5, 12, 4])
print(dat[dat > 10])

[123  12]


# Random

In [26]:
print(np.random.randint(0, 100))
print(np.random.randint(0, 100))

61
81


In [27]:
print(np.random.normal(0, 1, size=(3, 3)))

[[ 0.50683344 -1.08013169 -1.6357396 ]
 [ 1.01409702  2.34950031 -0.15511511]
 [-0.82921102 -2.84849444  1.471557  ]]


# Computation

In [28]:
dat = np.ones(3) + np.ones(3)
print(dat)

[2. 2. 2.]


In [29]:
dat = np.arange(5) * np.arange(5)
print(dat)

[ 0  1  4  9 16]


In [30]:
dat = np.arange(5)**2
print(dat)

[ 0  1  4  9 16]


In [31]:
dat = np.arange(5)**2 - np.arange(5)
print(dat)

[ 0  0  2  6 12]


In [32]:
dat = np.ones(5)
print(dat)

dat2 = np.cumsum(dat)
print(dat2)

[1. 1. 1. 1. 1.]
[1. 2. 3. 4. 5.]


In [33]:
dat = np.arange(5) @ np.ones(5)
print(dat)

10.0


In [34]:
dat = np.dot(np.arange(5), np.ones(5))
print(dat)

10.0


## Statistics

In [49]:
dat = np.ones(5)
mu = np.mean(dat)
std = np.std(dat)
print(f"mu={mu:.2f}, std={std:.2f}")

mu=1.00, std=0.00


In [50]:
dat = np.arange(5)
mu = np.mean(dat)
std = np.std(dat)
print(f"mu={mu:.2f}, std={std:.2f}")

mu=2.00, std=1.41


In [56]:
dat = np.random.uniform(0, 1, size=(5, 2))
mu = np.mean(dat, axis=0)
std = np.std(dat, axis=0)
print("mu")
print(mu)
print("std")
print(std)

mu
[0.54492918 0.46201055]
std
[0.22965026 0.23053451]


In [57]:
dat = np.random.uniform(0, 1, size=(5, 2))
mu = np.mean(dat, axis=1)
std = np.std(dat, axis=1)
print("mu")
print(mu)
print("std")
print(std)

mu
[0.74760488 0.70169699 0.33166571 0.62785862 0.3277738 ]
std
[0.11639548 0.148946   0.26830968 0.20494784 0.08089591]


In [59]:
dat = np.random.uniform(0, 1, size=(5, 2, 4))
mu = np.mean(dat, axis=(0, 2))
std = np.std(dat, axis=(0, 2))
print("mu")
print(mu)
print("std")
print(std)

mu
[0.47491941 0.49031476]
std
[0.29656193 0.25786723]
