# Numpy

The structure of this notebook is inspired by w3schools: https://www.w3schools.com/python/numpy/

NumPy = Numerical Python

What is numpy?
- A library for arrays
- Good for linear algebra
- Fast computation

Why use numpy?
- A lot faster than lists
- Often easier to use
- Great for data science

Code can be found here:
https://github.com/numpy/numpy


## Installation

In [1]:
!pip install numpy

## Importing numpy

In [2]:
import numpy as np

# Arrays

## Creating arrays from other data types

In [3]:
# Python list
dat = [1 ,3, 4, 5]
print(type(dat))
print(dat)

<class 'list'>
[1, 3, 4, 5]


In [4]:
# NumPy array from lists
dat = np.array([1 ,3, 4, 5])
print(type(dat))
print(dat)

<class 'numpy.ndarray'>
[1 3 4 5]


In [5]:
# NumPy array from tuples
dat = np.array((1 ,3, 4, 5))
print(type(dat))
print(dat)

<class 'numpy.ndarray'>
[1 3 4 5]


## Creating (multidimensional) arrays

In [6]:
# 0 dimensions
dat = np.array(1)
print(dat.ndim)
print(dat.shape)

0
()


In [7]:
# 1 dimension
dat = np.array([1, 3, 4])
print(dat.ndim)
print(dat.shape)

1
(3,)


In [8]:
# 2 dimensions
dat = np.array([[1, 3, 4], [10, 3, 4]])
print(dat.ndim)
print(dat.shape)

2
(2, 3)


In [9]:
# 3 dimensions
dat = np.array([[[1, 3, 4], [10, 3, 4], [1, 3, 4], [10, 3, 4]]])
print(dat.ndim)
print(dat.shape)

3
(1, 4, 3)


# Utility function for creating new arrays

You can set the shape and datatypes.

In [10]:
dat = np.ones((3, 4))
print(dat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
dat = np.zeros((3, 4), dtype=bool)
print(dat)

[[False False False False]
 [False False False False]
 [False False False False]]


In [12]:
dat = np.full((2, 2), 99)
print(dat)

[[99 99]
 [99 99]]


In [13]:
dat = np.arange(6)
print(dat)

[0 1 2 3 4 5]


# Indexing

## Simple indexing

In [14]:
# 1 d
dat = np.array([1, 2, 3, 4])
print(dat[0])

1


In [15]:
# 2 d
dat = np.array([[1, 3, 4], [10, 3, 5]])
print(dat[0, 0])
print(dat[1, 2])

1
5


## Negative indexing

In [16]:
# 1 d
dat = np.array([1, 2, 3, 4])
print(dat[-1])
print(dat[-2])

4
3


In [17]:
# 2 d
dat = np.array([[1, 3, 4], [10, 3, 5]])
print(dat[0, -1])
print(dat[-1, 0])

4
10


## Slicing

In [18]:
# 1 d
dat = np.array([1, 2, 3, 4, 5, 6])
print(dat[1:4])
print(dat[1:])
print(dat[:4])
print(dat[-3:])
print(dat[2:-2])
print(dat[-4:-2])
print(dat[:])

[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[4 5 6]
[3 4]
[3 4]
[1 2 3 4 5 6]


In [19]:
# 2 d
dat = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
print(dat[1:4, :])
print(dat[-1, 1:4])
print(dat[:, :-3])

[[1 2 3 4 5 6]]
[2 3 4]
[[1 2 3]
 [1 2 3]]


## Steps

In [20]:
# 1 d
dat = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(dat[0:-1:1])
print(dat[0:-1:2])
print(dat[0:-1:3])
print(dat[::1])

[1 2 3 4 5 6 7 8]
[1 3 5 7]
[1 4 7]
[1 2 3 4 5 6 7 8 9]


## Inverting order

In [21]:
arr = np.array([1, 2, 3])
arr2 = arr[::-1]
print(arr)
print(arr2)

[1 2 3]
[3 2 1]


# Data Types

Common types in Data Science:
- integer (int)
- float
- boolean
- unsigned integer (uint)
- strings


## Getting started

In [22]:
dat = np.array([1, 2, 3])
dat.dtype

dtype('int32')

In [23]:
dat = np.array([1.3, 2.2, 3.4])
dat.dtype

dtype('float64')

In [24]:
dat = np.array([1., 2., 3.])
dat.dtype

dtype('float64')

## Setting datatypes

In [25]:
dat = np.array([1, 2, 3], dtype=float)
dat.dtype

dtype('float64')

In [26]:
dat = np.array([1, 2, 3], dtype=np.float16)
dat.dtype

dtype('float16')

In [27]:
dat = np.array([1, 2, 3], dtype="uint")
dat.dtype

dtype('uint32')

In [28]:
dat = np.array(['a', 2, 3], dtype=str)
print(dat.dtype)
print(dat)

<U1
['a' '2' '3']


### Make sure to choose a datatype that matches the data you have

- Some data-types are automatically converted to other datatypes.
- Sometimes this conversion results in a loss of information.
- In some cases, there is no default conversion defined, resulting in an error.

In [29]:
# Underflow!
dat = np.array([-1, 2, 3], dtype="uint")
print(dat.dtype)
print(dat)

uint32
[4294967295          2          3]


In [30]:
# Rounding!
dat = np.array([1.99, 2, 3], dtype="int")
print(dat.dtype)
print(dat)

int32
[1 2 3]


In [31]:
# ValueError!
dat = np.array(['a', 2, 3], dtype=float)
print(dat.dtype)
print(dat)

ValueError: could not convert string to float: 'a'

# Copy and view

Be careful when changing data

In [32]:
dat = np.array([0, 1, 2, 3])
dat2 = dat
dat2[1] = 9

print(dat)
print(dat2)

[0 9 2 3]
[0 9 2 3]


In [33]:
dat = np.array([0, 1, 2, 3])
dat2 = dat[1:]

print(dat)
print(dat2)

dat2[1] = 9

print(dat)
print(dat2)

[0 1 2 3]
[1 2 3]
[0 1 9 3]
[1 9 3]


In [34]:
dat = np.array([0, 1, 2, 3])
dat2 = dat.copy()
dat2[1] = 9

print(dat)
print(dat2)

[0 1 2 3]
[0 9 2 3]


In [35]:
dat = np.array([0, 1, 2, 3])
dat2 = dat.view()
dat2[1] = 9

print(dat)
print(dat2)

[0 9 2 3]
[0 9 2 3]


In [36]:
def add_value(arr, val):  # Makes a copy
    arr = arr + val
    return arr

dat = np.array([0, 1, 2, 3])
dat2 = add_value(arr=dat, val=3)
print(dat)
print(dat2)

[0 1 2 3]
[3 4 5 6]


In [37]:
def add_value(arr, val):  # Does not make copy
    arr += val
    return arr

dat = np.array([0, 1, 2, 3])
dat2 = add_value(arr=dat, val=3)
print(dat)
print(dat2)

[3 4 5 6]
[3 4 5 6]


# Reshaping

In [38]:
dat = np.array([1, 2, 3, 4, 5, 6])

dat = dat.reshape((2, 3))
print(dat)

dat = dat.reshape((6, ))
print(dat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [39]:
dat = np.array([1, 2, 3, 4, 5, 6])
dat = dat.reshape((2, -1))
print(dat)

[[1 2 3]
 [4 5 6]]


In [40]:
dat = np.array([1, 2, 3, 4, 5, 6])
dat = dat.reshape((2, 2))

ValueError: cannot reshape array of size 6 into shape (2,2)

In [41]:
dat = np.array([[1, 2, 3], [4, 5, 6]])
dat = dat.flatten()
print(dat)

[1 2 3 4 5 6]


# Concatenate

In [42]:
dat1 = np.array([1, 2, 3])
dat2 = np.array([4, 5, 6])
dat = np.concatenate([dat1, dat2])
print(dat)

[1 2 3 4 5 6]
