In [1]:
import numpy as np

# New arrays

Create an array from an existing list

In [2]:
a_list = [1, 2, 3]
# Enter code here

Create an array with 3 names (strings)

In [3]:
# Enter code here

Create an array with zeros of size (20, 3). Print the data-type of the array.

In [4]:
# Enter code here

Create an array of numbers from 1 to 50 in descending order.
Do not just type the numbers.

Are there multiple ways you can implement this? If so, which approach seems best to you?

In [5]:
# Enter code here

Create an array that contains 50 times the number 1.5

In [6]:
# Enter code here

# Indexing

In python, indexing starts with 0, meaning that "arr[0]" will return the first element of the array

Index the number 3 in the following array

In [7]:
arr = np.arange(5)
print(arr)
# Enter code here

[0 1 2 3 4]


Use negative indexing to index the number 4 in the following array

In [8]:
arr = np.arange(5)
print(arr)
# Enter code here

[0 1 2 3 4]


# Other

Reshape the following array to a 1d array with all four values in ascending order.

In [9]:
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(arr.shape)
# Enter code here

[[1 2]
 [3 4]]
(2, 2)


Try the same with the following array.

In [10]:
arr = np.array([[2, 1], [4, 3]])
print(arr)
print(arr.shape)
# Enter code here

[[2 1]
 [4 3]]
(2, 2)


Create two 1d arrays and concatenate them

In [11]:
# Enter code here

Create two 2d arrays and concatenate them.

In [12]:
# Enter code here

Create two 2d arrays for which the concatenate function will not work (without reshaping)

In [13]:
# Enter code here

Change the first value in "dat2", then inspect "dat".

In [14]:
dat = np.arange(5)
dat2 = dat
print(dat)
print(dat2)

# Enter code here

print(dat)
print(dat2)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


Make a copy of the following array using the "copy" function and change the first value in your copy.
Confirm that the original array was not changed.

In [15]:
dat = np.arange(5)
print(dat)
# Enter code here

[0 1 2 3 4]
